trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ARM_CLIENT_ID: '4725e74c-bf04-411a-ac66-b80ba4857b04'
  ARM_CLIENT_SECRET: 'm0o8Q~QA~n1xjzKTRxh2zDNvHJnHpgjJKlfEFaaX'
  ARM_SUBSCRIPTION_ID: '467d1c24-a75f-489f-bb4c-d8300586e65e'
  ARM_TENANT_ID: '88305003-440b-4e88-9574-2533eeb2a273'
  TF_VAR_storage_account_name: 'bradwillztstate'
  TF_VAR_container_name: 'tstate'

stages:
- stage: Terraform
  jobs:
  - job: Terraform
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        curl -LO https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
        unzip terraform_1.0.0_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
      displayName: 'Install Terraform'

    - script: terraform init
      displayName: 'Terraform INIT'

    - script: terraform plan
      displayName: 'Terraform PLAN'

    - script: terraform validate
      displayName: 'Terraform VALIDATE'

    - script: terraform apply -auto-approve
      displayName: 'Terraform APPLY'